In [ ]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


# Sintaxe básica do Pytorch

Assim como o NumPy, o Pytorch é uma biblioteca de processamento vetorial/matricial/tensorial. Operações sobre os tensores do Pytorch possuem sintaxe consideravelmente parecida com operações sobre tensores do NumPy.

Para mais informações sobre tensores em PyTorch, consulte a documentação: <br> https://pytorch.org/docs/stable/tensors.html



## Tipos de tensores 

Você pode criar tensores do PyTorch de inúmeras formas! Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. Para isso, vamos converter listas comuns do Python em tensors do PyTorch.

Note que a impressão de tensores dos tipos ```float32``` e ```int64``` não vêm acompanhadas do parâmetro de tipo ```dtype```, visto que se tratam dos tipos padrão trabalhados pelo PyTorch.

In [ ]:
import torch
lista = [ [1,2,3],
          [4,5,6] ]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

print('')
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

print('')
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


## Outras formas de instanciar tensores

### A partir de arrays Numpy
$torch.from\_numpy()$ 



In [ ]:
import numpy as np

arr = np.random.rand(3,4)
# arr = arr.astype(int)
print(arr)
print(arr.dtype)

print('')
tns = torch.from_numpy(arr)
print(tns)
print(tns.dtype)

[[0.79278742 0.42132155 0.00879431 0.03859303]
 [0.87670825 0.79678101 0.68851749 0.23491561]
 [0.15545066 0.97506283 0.83242432 0.05884273]]
float64

tensor([[0.7928, 0.4213, 0.0088, 0.0386],
        [0.8767, 0.7968, 0.6885, 0.2349],
        [0.1555, 0.9751, 0.8324, 0.0588]], dtype=torch.float64)
torch.float64


### Tensores inicializados
Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

$torch.ones()$ -> Cria um tensor preenchido com zeros.

$torch.zeros()$ -> Cria um tensor preenchido com uns.

$torch.randn()$ -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal.

In [ ]:
tns1 = torch.ones(2, 3)
tns0 = torch.zeros(3, 5)
tnsr = torch.randn(3, 3)

print(tns1)
print()
print(tns0)
print()
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

tensor([[ 0.9556, -0.0920,  0.3814],
        [ 1.1769, -0.7666, -1.3371],
        [-0.9476,  1.0692,  0.6045]])


### Tensor para array numpy

In [ ]:
arr = tnsr
print(arr)
print(type(arr))

tensor([[ 0.9556, -0.0920,  0.3814],
        [ 1.1769, -0.7666, -1.3371],
        [-0.9476,  1.0692,  0.6045]])
<class 'torch.Tensor'>


In [ ]:
arr = tnsr.data.numpy()
print(arr)
print(type(arr))

[[ 0.95564306 -0.09202313  0.3813985 ]
 [ 1.1769122  -0.7665986  -1.3371354 ]
 [-0.94758606  1.0691699   0.60451424]]
<class 'numpy.ndarray'>


## Indexação

De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sintaxe de colchetes ```[]```.

In [ ]:
# indexar == acessar
print(tnsr)
tnsr[1,2] = 00.3333

print()

print(tnsr)

print()

print(tnsr[:, 2])

print()

print(tnsr[0:2])

tensor([[ 0.9556, -0.0920,  0.3814],
        [ 1.1769, -0.7666, -1.3371],
        [-0.9476,  1.0692,  0.6045]])

tensor([[ 0.9556, -0.0920,  0.3814],
        [ 1.1769, -0.7666,  0.3333],
        [-0.9476,  1.0692,  0.6045]])

tensor([0.3814, 0.3333, 0.6045])

tensor([[ 0.9556, -0.0920,  0.3814],
        [ 1.1769, -0.7666,  0.3333]])


In [ ]:
# tnsr[0,1]

print(tnsr[0:2, 2].data.numpy())
print(tnsr[0, 1].item())

[0.3813985 0.3333   ]
-0.09202313423156738


## Operações com tensores

A função ```.item()``` utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar as operações numéricas do Python. Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas **ponto a ponto**, operando cada elemento ```(i, j)``` do tensor ```t1```, com o elemento ```(i, j)``` do tensor ```t2```.

In [ ]:
tns1 = torch.randn(2,2,3)
tns2 = torch.ones(2,2,3)

print(tns1)
print(tns2)

print('')

print(tns1*tns2)

tensor([[[-0.2146,  0.2766, -0.1327],
         [ 1.6839,  1.1370, -0.5611]],

        [[-1.4219,  0.6461,  2.4023],
         [ 0.2043, -0.3392, -0.8230]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

tensor([[[-0.2146,  0.2766, -0.1327],
         [ 1.6839,  1.1370, -0.5611]],

        [[-1.4219,  0.6461,  2.4023],
         [ 0.2043, -0.3392, -0.8230]]])


In [ ]:
tns2.shape

torch.Size([2, 2, 3])

In [ ]:
tns1.shape

torch.Size([2, 2, 3])

## Função ```.size()``` e ```.view()```

Uma operações **importantíssima** na manipulação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, **linearizar um tensor n-dimensional**.

In [ ]:
tns = torch.randn(2,2,3)
print(tns)
print(tns.size())

tensor([[[-0.5372,  1.2174, -1.7088],
         [-0.8526, -1.1299, -1.3625]],

        [[ 0.4519, -0.3452, -2.3278],
         [ 1.4025, -0.3334, -0.0611]]])
torch.Size([2, 2, 3])


achatamento

In [ ]:
tns = tns.view(12)
print(tns)

tensor([-0.5372,  1.2174, -1.7088, -0.8526, -1.1299, -1.3625,  0.4519, -0.3452,
        -2.3278,  1.4025, -0.3334, -0.0611])


In [ ]:
tns = tns.view(-1)
print(tns)

tensor([-0.5372,  1.2174, -1.7088, -0.8526, -1.1299, -1.3625,  0.4519, -0.3452,
        -2.3278,  1.4025, -0.3334, -0.0611])


In [ ]:
tns = tns.view(4,3)
print(tns)

tensor([[-0.5372,  1.2174, -1.7088],
        [-0.8526, -1.1299, -1.3625],
        [ 0.4519, -0.3452, -2.3278],
        [ 1.4025, -0.3334, -0.0611]])


tamanho e achatamento

In [ ]:
print(tns2.size())

print(tns2.view(tns2.size(0), -1)) # mantem a primeira dimensao e achata o resto 

torch.Size([2, 2, 3])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


## GPU Cast

Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisarmos subir valores na GPU, como os pesos da rede, os gradientes, etc.

In [ ]:
import torch
if torch.cuda.is_available(): #GPU esta dispnivel?
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)

cpu


In [ ]:
import torch
if torch.cuda.is_available(): #GPU esta dispnivel?
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
  
print(device)

print('=='*30)

tns = tns.to(device) # jogando a variavel na GPU == cuda
print(tns)

cuda
tensor([[-0.6919,  1.0432, -0.4097],
        [-0.1040,  0.9651, -1.8367],
        [-1.6184, -0.0631,  0.6176],
        [-1.0652, -0.6006,  0.4474]], device='cuda:0')


In [ ]:
tns_out = torch.cat( (tns1, tns1), dim=0 )

In [ ]:
tns_out

tensor([[[ 2.5533e+00, -1.7464e-01, -5.4974e-01],
         [ 1.6209e+00, -9.0534e-01, -3.2231e-01]],

        [[ 1.9457e-03, -1.3335e+00,  1.2358e+00],
         [-5.1070e-01, -4.6594e-02,  2.5468e+00]],

        [[ 2.5533e+00, -1.7464e-01, -5.4974e-01],
         [ 1.6209e+00, -9.0534e-01, -3.2231e-01]],

        [[ 1.9457e-03, -1.3335e+00,  1.2358e+00],
         [-5.1070e-01, -4.6594e-02,  2.5468e+00]]])

Para realizar o produto interno de tensores 2D, o Pytorch possui a função torch.mm(tns1, tns2), que recebe como parâmetro os dois tensores a serem operados e retorna o resultado do produto. Para que o produto seja possível, o tensor tns1 deve ser (n x m) e tns2 (m x p), sendo o resultado um tensor (n x p).

Observe o seguinte código:

In [ ]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


Nesta aula nos familiarizamos com o ambiente do Google Colab à medida que introduzimos a sintaxe básica do PyTorch para manipulação de tensores. Para trabalhar com redes neurais, a sua principal preocupação em relação aos tensores é garantir que sua dimensionalidade seja consistente com a operação que se deseja realizar.

Pensando nisso, crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores.

In [ ]:
## Resumo do código
import torch 
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2

In [ ]:
soma